### ISSUE TITLE
Uncaught TypeError: _ref1.getPath is not a function

### ISSUE THREAD

**Issue by jnordwick** [nguyenchr/atom-cargo-test-runner#7]
[Enter steps to reproduce below:]
1. Run a test. It happens on all of them.

**Atom Version**: 1.1.0
**System**: Linux Mint
**Thrown From**: [cargo-test-runner](https://github.com/nguyenchr/atom-cargo-test-runner) package, v0.0.4
### Stack Trace

Uncaught TypeError: _ref1.getPath is not a function

```
At /home/jnordwick/.atom/packages/cargo-test-runner/lib/clickable-paths.coffee:30

TypeError: _ref1.getPath is not a function
  at Object.module.exports.open (/home/jnordwick/.atom/packages/cargo-test-runner/lib/clickable-paths.coffee:30:31)
  at HTMLAnchorElement.module.exports.clicked (/home/jnordwick/.atom/packages/cargo-test-runner/lib/clickable-paths.coffee:20:18)
  at HTMLAnchorElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLAnchorElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -3:32.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:22.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:35.8.0 core:undo (atom-text-editor.editor.is-focused)
     -2:34.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:33.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:28.3.0 core:save (atom-text-editor.editor.is-focused)
  4x -2:22.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:13.9.0 core:save (atom-text-editor.editor.is-focused)
 10x -1:49.2.0 core:undo (atom-text-editor.editor.is-focused)
  3x -1:40 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:39.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:17.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:14 core:undo (atom-text-editor.editor.is-focused)
 10x -1:11.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:02.0 core:save (atom-text-editor.editor.is-focused)
     -0:29.3.0 cargo-test-runner:run (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": []
  }
}
```
### Installed Packages

``` coffee
# User
build-cargo, v0.6.0
cargo-test-runner, v0.0.4
language-rust, v0.4.5
racer, v0.17.2
rust-api-docs-helper, v0.5.1

# Dev
No dev packages
```

**Comment by colin-kiegel** [comment]
Happens with atom 1.2.3, too.

The stack trace is the same, but the line number changed from 30 to 41
~/.atom/packages/cargo-test-runner/lib/clickable-paths.coffee:41

```
TypeError: _ref1.getPath is not a function
    at Object.module.exports.open (/home/colin/.atom/packages/cargo-test-runner/lib/clickable-paths.coffee:41:58)
    at HTMLAnchorElement.module.exports.clicked (/home/colin/.atom/packages/cargo-test-runner/lib/clickable-paths.coffee:28:27)
    at HTMLAnchorElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLAnchorElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by bklooste** [comment]
Me as well , project in ~/src

**Comment by nguyenchr** [comment]
`0.0.5` now published, please see if this fixes your issues
